#### Numpy Arrays and Operations

## Why use MEAN,STANDARD DEVIATION AND RESHAPING

# Mean
- Gives summary of dataset
-Used in Normalization
-Used in ML algorithms(e.g feature scaling)

# Standard deviation
- Helps detect outliers
- Used in normalization
-Shows staability of data
-Tells which feature varies the most

# Reshaping
- Only changing the arrangement not the data
-It ensure compatibility with linear regression e.t.c.
- When preparing data for training



In [ ]:
import numpy as np #Becuase Numpy handles fast numerical  computation using arrays(Vectors,matrices)
import pandas as pd

#Load the data

df = pd.read_csv("cleaned_data.csv")

#Making sure the numeric columns are actually numeric
df[["Duration","Pulse","Maxpulse","Calories"]].info()




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  30 non-null     int64  
 1   Pulse     30 non-null     int64  
 2   Maxpulse  30 non-null     int64  
 3   Calories  30 non-null     float64
dtypes: float64(1), int64(3)
memory usage: 1.1 KB


numpy.ndarray

## Creating 1D Array

The 1D array represents a single numerical feature extracted from the dataset (e.g Calories).

shape: (30,)
It contains 30 values arranged in a single line.
Each value corresponds to one workout session.
This structure isuseful for calculating statistical measures like mean and standard deviation.

In [ ]:
# Step 1: Creating 1D array
calories = df["Calories"].to_numpy()

#To check the type if it's an array use-type(calories)
#To check the array dimension use-calories.ndim
#To check the shape of the array use-calories.shape







1

My 1D array represents Calories per session

Calculating the Mean and Standard deviation of the 1D Array

In [10]:

#Calculating the Mean
display(np.mean(calories))

#Calculating the Standard deviation
display(np.std(calories))  #If small consistent workouts,if large inconsistent intensity


#Shaping 1D array
display(calories.reshape(-1,1))

np.float64(306.9233333333333)

np.float64(63.979963964423185)

array([[409.1],
       [479. ],
       [340. ],
       [282.4],
       [406. ],
       [300. ],
       [374. ],
       [253.3],
       [195.1],
       [269. ],
       [329.3],
       [250.7],
       [345.3],
       [379.3],
       [275. ],
       [215.2],
       [300. ],
       [300. ],
       [323. ],
       [243. ],
       [364.2],
       [300. ],
       [246. ],
       [334.5],
       [250. ],
       [241. ],
       [300. ],
       [280. ],
       [380.3],
       [243. ]])

#### Creating a 2D Array

The 2D array represents multiple numerical features combined into one matrix.

In [12]:
#Creating 2D array
features = df[["Duration","Pulse","Maxpulse","Calories"]].to_numpy()
display(np.mean(features,0)) #Mean of each column why it is 0

#Standard deviation for 2D array columns
display(np.std(features,0))

#Reshaping 
calories_reshaped = calories.reshape(-1,1)
display(calories_reshaped.shape)



array([ 69.5       , 103.73333333, 129.1       , 306.92333333])

array([71.04400045,  7.90752103, 12.99320335, 63.97996396])

(30, 1)

## Why use MEAN,STANDARD DEVIATION AND RESHAPING

# Mean
- Gives summary of dataset
-Used in Normalization
-Used in ML algorithms(e.g feature scaling)

# Standard deviation
- Helps detect outliers
- Used in normalization
-Shows staability of data
-Tells which feature varies the most

# Reshaping
- Only changing the arrangement not the data
-It ensure compatibility with linear regression e.t.c.
- When preparing data for training

